INSERT INTO exercises (name, slug, muscle_group_primary, muscle_groups_secondary, equipment, movement_pattern, is_bilateral, difficulty_level, cues, is_global) VALUES
('Press Banca con Barra','press-banca-barra','pecho',ARRAY['triceps','deltoides anterior'],'barra','push',TRUE,2,ARRAY['Retrae escápulas','Pies en el suelo','Arco neutro','Codos 75°'],TRUE),
('Press Banca con Mancuernas','press-banca-mancuernas','pecho',ARRAY['triceps','deltoides anterior'],'mancuernas','push',TRUE,2,ARRAY['Mayor rango de movimiento','Controla la bajada'],TRUE),
('Press Inclinado con Barra','press-inclinado-barra','pecho',ARRAY['deltoides anterior','triceps'],'barra','push',TRUE,3,ARRAY['30-45° de inclinación','Escápulas retraídas'],TRUE),
('Aperturas con Mancuernas','aperturas-mancuernas','pecho',ARRAY['deltoides anterior'],'mancuernas','isolation',TRUE,2,ARRAY['Codos ligeramente flexionados','Movimiento de abrazo'],TRUE),
('Crossover en Polea Alta','crossover-polea-alta','pecho',ARRAY['deltoides anterior'],'polea','isolation',TRUE,2,ARRAY['Contracción en la cruz','Codos fijos'],TRUE),
('Fondos en Paralelas','fondos-paralelas','pecho',ARRAY['triceps','deltoides anterior'],'peso_corporal','push',TRUE,3,ARRAY['Inclina el torso adelante para pecho'],TRUE),
('Dominadas Pronadas','dominadas-pronadas','espalda',ARRAY['biceps','deltoides posterior'],'barra','pull',TRUE,3,ARRAY['Deprime las escápulas primero','No uses inercia'],TRUE),
('Dominadas Supinas','dominadas-supinas','espalda',ARRAY['biceps'],'barra','pull',TRUE,3,ARRAY['Mayor activación de bíceps','Pecho al frente'],TRUE),
('Remo con Barra','remo-barra','espalda',ARRAY['biceps','trapecio'],'barra','pull',TRUE,3,ARRAY['Espalda recta 45°','Codos pegados al cuerpo'],TRUE),
('Jalón al Pecho','jalon-pecho','espalda',ARRAY['biceps','deltoides posterior'],'polea','pull',TRUE,2,ARRAY['Inclínate ligeramente','Lleva el peso al esternón'],TRUE),
('Remo con Mancuerna','remo-mancuerna','espalda',ARRAY['biceps','romboides'],'mancuernas','pull',FALSE,2,ARRAY['Rodilla y mano de apoyo','Codo pegado'],TRUE),
('Remo en Máquina','remo-maquina','espalda',ARRAY['biceps','trapecio'],'maquina','pull',TRUE,1,ARRAY['Ajusta el asiento','Retrae escápulas'],TRUE),
('Face Pull','face-pull','deltoides posterior',ARRAY['trapecio','romboides'],'polea','pull',TRUE,2,ARRAY['Polea a altura de la cara','Externaliza los hombros'],TRUE),
('Peso Muerto Convencional','peso-muerto-convencional','espalda',ARRAY['gluteos','isquiotibiales','trapecio'],'barra','hinge',TRUE,4,ARRAY['Barra sobre el medio del pie','Espalda neutra'],TRUE),
('Press Militar con Barra','press-militar-barra','deltoides anterior',ARRAY['triceps','trapecio'],'barra','push',TRUE,3,ARRAY['Core activo','No hiperextiendas lumbar'],TRUE),
('Press con Mancuernas Hombros','press-mancuernas-hombros','deltoides anterior',ARRAY['triceps'],'mancuernas','push',TRUE,2,ARRAY['Mayor ROM que barra','Codos 90° en inicio'],TRUE),
('Elevaciones Laterales','elevaciones-laterales','deltoides lateral',ARRAY[]::TEXT[],'mancuernas','isolation',FALSE,2,ARRAY['Ligeramente inclinado adelante','No superes la horizontal'],TRUE),
('Elevaciones Frontales','elevaciones-frontales','deltoides anterior',ARRAY[]::TEXT[],'mancuernas','isolation',FALSE,2,ARRAY['Agarre neutro o pronado','Controla la bajada'],TRUE),
('Curl con Barra','curl-barra','biceps',ARRAY['braquial'],'barra','isolation',TRUE,2,ARRAY['Codos fijos','Supinación al subir'],TRUE),
('Curl con Mancuernas Alternado','curl-mancuernas-alternado','biceps',ARRAY['braquial'],'mancuernas','isolation',FALSE,2,ARRAY['Supina la muñeca al subir','Sin balanceo'],TRUE),
('Curl en Predicador','curl-predicador','biceps',ARRAY[]::TEXT[],'maquina','isolation',FALSE,2,ARRAY['Máximo estiramiento','No bloquees en la baja'],TRUE),
('Curl Martillo','curl-martillo','braquial',ARRAY['biceps','braquiorradial'],'mancuernas','isolation',FALSE,2,ARRAY['Agarre neutro todo el movimiento'],TRUE),
('Press Francés','press-frances','triceps',ARRAY[]::TEXT[],'barra','isolation',TRUE,3,ARRAY['Codos fijos apuntando al techo','Máximo estiramiento'],TRUE),
('Press de Tríceps en Polea','press-triceps-polea','triceps',ARRAY[]::TEXT[],'polea','isolation',TRUE,1,ARRAY['Codos pegados al cuerpo','Extiende completamente'],TRUE),
('Rompecráneos','rompecraneos','triceps',ARRAY[]::TEXT[],'barra','isolation',TRUE,3,ARRAY['Barra a la frente o detrás','Carga muy efectiva para masa'],TRUE),
('Sentadilla con Barra Alta','sentadilla-barra-alta','cuadriceps',ARRAY['gluteos','isquiotibiales'],'barra','squat',TRUE,4,ARRAY['Rodillas siguen los pies','Profundidad completa'],TRUE),
('Sentadilla con Barra Baja','sentadilla-barra-baja','gluteos',ARRAY['cuadriceps','isquiotibiales'],'barra','squat',TRUE,4,ARRAY['Mayor inclinación de torso','Énfasis en cadera'],TRUE),
('Prensa de Piernas','prensa-piernas','cuadriceps',ARRAY['gluteos'],'maquina','squat',TRUE,2,ARRAY['Pies altos = glúteo','Pies bajos = cuád'],TRUE),
('Extensiones de Cuádriceps','extensiones-cuadriceps','cuadriceps',ARRAY[]::TEXT[],'maquina','isolation',FALSE,1,ARRAY['Extensión completa','Contrae en el tope'],TRUE),
('Hack Squat','hack-squat','cuadriceps',ARRAY['gluteos'],'maquina','squat',TRUE,3,ARRAY['Alta tensión en cuádriceps'],TRUE),
('Peso Muerto Rumano','peso-muerto-rumano','isquiotibiales',ARRAY['gluteos'],'barra','hinge',TRUE,3,ARRAY['Bisagra de cadera','Rodillas ligeramente flexionadas'],TRUE),
('Curl Femoral Tumbado','curl-femoral-tumbado','isquiotibiales',ARRAY[]::TEXT[],'maquina','isolation',TRUE,1,ARRAY['Contrae en el tope','Rango completo'],TRUE),
('Curl Femoral Sentado','curl-femoral-sentado','isquiotibiales',ARRAY[]::TEXT[],'maquina','isolation',TRUE,1,ARRAY['Mayor estiramiento que tumbado'],TRUE),
('Hip Thrust con Barra','hip-thrust-barra','gluteos',ARRAY['isquiotibiales'],'barra','hinge',TRUE,3,ARRAY['Espalda sobre el banco','Aprieta glúteo arriba'],TRUE),
('Elevaciones de Talones de Pie','elevaciones-talones-pie','gemelos',ARRAY[]::TEXT[],'maquina','isolation',TRUE,1,ARRAY['Rango completo','Pausa en el estiramiento'],TRUE),
('Elevaciones de Talones Sentado','elevaciones-talones-sentado','soleo',ARRAY[]::TEXT[],'maquina','isolation',TRUE,1,ARRAY['Énfasis en sóleo','Rodilla 90°'],TRUE),
('Plancha Abdominal','plancha-abdominal','core',ARRAY['gluteos'],'peso_corporal','carry',TRUE,1,ARRAY['Cuerpo recto','Aprieta glúteo'],TRUE),
('Crunch en Polea','crunch-polea','core',ARRAY[]::TEXT[],'polea','isolation',TRUE,2,ARRAY['Flexión lumbar','Contrae el abdomen'],TRUE),
('Abdominales en Rueda','abdominales-rueda','core',ARRAY['dorsales','hombros'],'peso_corporal','carry',TRUE,4,ARRAY['Empieza de rodillas','Core muy tenso'],TRUE),
('Zancadas con Barra','zancadas-barra','cuadriceps',ARRAY['gluteos','isquiotibiales'],'barra','squat',FALSE,3,ARRAY['Paso largo','Rodilla trasera cerca del suelo'],TRUE),
('Buenos Días','buenos-dias','isquiotibiales',ARRAY['gluteos','espalda'],'barra','hinge',TRUE,4,ARRAY['Bisagra de cadera','Espalda neutra'],TRUE),
('Press Inclinado Mancuernas','press-inclinado-mancuernas','pecho',ARRAY['deltoides anterior'],'mancuernas','push',TRUE,2,ARRAY['Mayor ROM','Controla la negativa'],TRUE),
('Press en Máquina Pecho','press-maquina-pecho','pecho',ARRAY['triceps'],'maquina','push',TRUE,1,ARRAY['Ajusta el asiento','Controla la negativa'],TRUE),
('Patada de Tríceps','patada-triceps','triceps',ARRAY[]::TEXT[],'mancuernas','isolation',FALSE,2,ARRAY['Codo fijo paralelo al suelo','Extensión completa'],TRUE),
('Dead Bug','dead-bug','core',ARRAY[]::TEXT[],'peso_corporal','carry',TRUE,2,ARRAY['Zona lumbar pegada al suelo','Movimiento contralateral'],TRUE);
